/**
 * Global Drone/UAS Regulatory Authorities
 *
 * Source of truth for country-specific onboarding in C6mac Sky Warden.
 * Auto-populates the correct regulatory authority, regulations, locale
 * settings, and emergency contacts based on the user's country.
 *
 * Covers 69 countries across 6 regions.
 *
 * Data verified against official sources as of Q1 2026.
 */

import type { CountryAuthority } from '../types/regulatory';

export const GLOBAL_REGULATORY_AUTHORITIES: CountryAuthority[] = [
  // ═══════════════════════════════════════════════════════════════════
  // NORTH AMERICA (3)
  // ═══════════════════════════════════════════════════════════════════

  {
    countryCode: 'US',
    countryName: 'United States',
    flagEmoji: '\u{1F1FA}\u{1F1F8}',
    region: 'north_america',
    authority: {
      name: 'Federal Aviation Administration',
      acronym: 'FAA',
      website: 'https://www.faa.gov/uas',
      registrationPortal: 'https://faadronezone.faa.gov',
    },
    regulations: {
      primaryRegulation: '14 CFR Part 107',
      pilotCertName: 'Remote Pilot Certificate (Part 107)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: '14 CFR Part 89',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: 'LAANC',
      authorizationSystem: 'LAANC / DroneZone',
    },
    locale: {
      currency: 'USD',
      dateFormat: 'MM/DD/YYYY',
      timeFormat: '12h',
      distanceUnit: 'feet',
      altitudeUnit: 'feet',
      speedUnit: 'mph',
      weightUnit: 'pounds',
      temperatureUnit: 'fahrenheit',
    },
    emergencyNumber: '911',
    aviationEmergency: '1-866-835-5322',
  },

  {
    countryCode: 'CA',
    countryName: 'Canada',
    flagEmoji: '\u{1F1E8}\u{1F1E6}',
    region: 'north_america',
    authority: {
      name: 'Transport Canada Civil Aviation',
      acronym: 'TCCA',
      website: 'https://tc.canada.ca/en/aviation/drone-safety',
      registrationPortal: 'https://tc.canada.ca/en/aviation/drone-safety/drone-management-portal',
    },
    regulations: {
      primaryRegulation: 'Canadian Aviation Regulations Part IX',
      pilotCertName: 'Pilot Certificate - Basic / Advanced / Level 1 Complex',
      registrationRequired: true,
      remoteIdRequired: 'planned',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: 'NAV CANADA Drone Flight Planning',
      authorizationSystem: 'NAV CANADA / Drone Management Portal',
    },
    locale: {
      currency: 'CAD',
      dateFormat: 'YYYY-MM-DD',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '911',
    aviationEmergency: '1-800-305-2059',
  },

  {
    countryCode: 'MX',
    countryName: 'Mexico',
    flagEmoji: '\u{1F1F2}\u{1F1FD}',
    region: 'north_america',
    authority: {
      name: 'Agencia Federal de Aviacion Civil',
      acronym: 'AFAC',
      website: 'https://www.gob.mx/afac',
      registrationPortal: 'https://www.gob.mx/afac/acciones-y-programas/rpas-drones',
    },
    regulations: {
      primaryRegulation: 'NOM-107-SCT3-2019 / CO AV-23/10 R4',
      pilotCertName: 'Licencia de Piloto de RPAS',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'AFAC RPAS Portal',
    },
    locale: {
      currency: 'MXN',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '911',
    aviationEmergency: '55-5723-9300',
  },

  // ═══════════════════════════════════════════════════════════════════
  // EUROPE (16)
  // ═══════════════════════════════════════════════════════════════════

  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flagEmoji: '\u{1F1EC}\u{1F1E7}',
    region: 'europe',
    authority: {
      name: 'Civil Aviation Authority',
      acronym: 'CAA',
      website: 'https://www.caa.co.uk/drones',
      registrationPortal: 'https://register-drones.caa.co.uk',
    },
    regulations: {
      primaryRegulation: 'Air Navigation Order 2016 / ANO Article 94A-95',
      pilotCertName: 'Flyer ID / Operator ID',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'CAP 2568 Remote Identification',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAA Drone Registration Service',
    },
    locale: {
      currency: 'GBP',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'mph',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: '01011-22-1234',
  },

  {
    countryCode: 'FR',
    countryName: 'France',
    flagEmoji: '\u{1F1EB}\u{1F1F7}',
    region: 'europe',
    authority: {
      name: 'Direction Generale de l\'Aviation Civile',
      acronym: 'DGAC',
      website: 'https://www.ecologie.gouv.fr/politiques-publiques/drones-aeronefs-telecommandes',
      registrationPortal: 'https://alphatango.aviation-civile.gouv.fr',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA) + National Arretes',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'AlphaTango / Geoportail',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'DE',
    countryName: 'Germany',
    flagEmoji: '\u{1F1E9}\u{1F1EA}',
    region: 'europe',
    authority: {
      name: 'Luftfahrt-Bundesamt',
      acronym: 'LBA',
      website: 'https://www.lba.de/EN/Drones/Drones_node.html',
      registrationPortal: 'https://uas-registration.lba-openuav.de',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA) + LuftVO',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'dipul.de / LBA UAS Registration',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD.MM.YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'ES',
    countryName: 'Spain',
    flagEmoji: '\u{1F1EA}\u{1F1F8}',
    region: 'europe',
    authority: {
      name: 'Agencia Estatal de Seguridad Aerea',
      acronym: 'AESA',
      website: 'https://www.seguridadaerea.gob.es/en/ambitos/drones',
      registrationPortal: 'https://www.seguridadaerea.gob.es/en/ambitos/drones/operaciones-uas',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA) + RD 517/2024',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'AESA UAS Portal',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'IT',
    countryName: 'Italy',
    flagEmoji: '\u{1F1EE}\u{1F1F9}',
    region: 'europe',
    authority: {
      name: 'Ente Nazionale per l\'Aviazione Civile',
      acronym: 'ENAC',
      website: 'https://www.enac.gov.it/sicurezza-aerea/droni',
      registrationPortal: 'https://www.d-flight.it',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA) + Regolamento UAS-IT',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'D-Flight UTM Platform',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    flagEmoji: '\u{1F1F3}\u{1F1F1}',
    region: 'europe',
    authority: {
      name: 'Inspectie Leefomgeving en Transport',
      acronym: 'ILT',
      website: 'https://www.ilent.nl/onderwerpen/drone',
      registrationPortal: 'https://registratie.rwsleefomgeving.nl/drone',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ILT UAS Portal',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD-MM-YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'SE',
    countryName: 'Sweden',
    flagEmoji: '\u{1F1F8}\u{1F1EA}',
    region: 'europe',
    authority: {
      name: 'Transportstyrelsen',
      acronym: 'TAS',
      website: 'https://www.transportstyrelsen.se/en/aviation/Unmanned-aircraft---drones/',
      registrationPortal: 'https://e-tjanster.transportstyrelsen.se',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Transportstyrelsen UAS Portal',
    },
    locale: {
      currency: 'SEK',
      dateFormat: 'YYYY-MM-DD',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'NO',
    countryName: 'Norway',
    flagEmoji: '\u{1F1F3}\u{1F1F4}',
    region: 'europe',
    authority: {
      name: 'Civil Aviation Authority Norway',
      acronym: 'CAA Norway',
      website: 'https://luftfartstilsynet.no/en/drones/',
      registrationPortal: 'https://luftfartstilsynet.no/en/drones/registration/',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Luftfartstilsynet UAS Portal',
    },
    locale: {
      currency: 'NOK',
      dateFormat: 'DD.MM.YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'DK',
    countryName: 'Denmark',
    flagEmoji: '\u{1F1E9}\u{1F1F0}',
    region: 'europe',
    authority: {
      name: 'Trafikstyrelsen',
      acronym: 'DTA',
      website: 'https://www.trafikstyrelsen.dk/en/aviation/unmanned-aircraft-drones',
      registrationPortal: 'https://www.trafikstyrelsen.dk/en/aviation/unmanned-aircraft-drones',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Trafikstyrelsen UAS Portal',
    },
    locale: {
      currency: 'DKK',
      dateFormat: 'DD-MM-YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'FI',
    countryName: 'Finland',
    flagEmoji: '\u{1F1EB}\u{1F1EE}',
    region: 'europe',
    authority: {
      name: 'Finnish Transport and Communications Agency',
      acronym: 'Traficom',
      website: 'https://www.traficom.fi/en/transport/aviation/drones',
      registrationPortal: 'https://www.droneinfo.fi',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Droneinfo.fi',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD.MM.YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    flagEmoji: '\u{1F1E8}\u{1F1ED}',
    region: 'europe',
    authority: {
      name: 'Federal Office of Civil Aviation',
      acronym: 'FOCA',
      website: 'https://www.bazl.admin.ch/bazl/en/home/drohnen.html',
      registrationPortal: 'https://www.bazl.admin.ch/bazl/en/home/drohnen.html',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA) via bilateral agreement',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'FOCA / U-Space Switzerland',
    },
    locale: {
      currency: 'CHF',
      dateFormat: 'DD.MM.YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'IE',
    countryName: 'Ireland',
    flagEmoji: '\u{1F1EE}\u{1F1EA}',
    region: 'europe',
    authority: {
      name: 'Irish Aviation Authority',
      acronym: 'IAA',
      website: 'https://www.iaa.ie/general-aviation/drones',
      registrationPortal: 'https://www.iaa.ie/general-aviation/drones/registration',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA) + SI No. 563/2020',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'IAA MySRS Drone Portal',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'PL',
    countryName: 'Poland',
    flagEmoji: '\u{1F1F5}\u{1F1F1}',
    region: 'europe',
    authority: {
      name: 'Urzad Lotnictwa Cywilnego',
      acronym: 'ULC',
      website: 'https://www.ulc.gov.pl/en/unmanned-aircraft',
      registrationPortal: 'https://drony.ulc.gov.pl',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ULC Drone Portal (drony.ulc.gov.pl)',
    },
    locale: {
      currency: 'PLN',
      dateFormat: 'DD.MM.YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'BE',
    countryName: 'Belgium',
    flagEmoji: '\u{1F1E7}\u{1F1EA}',
    region: 'europe',
    authority: {
      name: 'Direction Generale Transport Aerien',
      acronym: 'DGTA',
      website: 'https://mobilit.belgium.be/en/aviation/drones',
      registrationPortal: 'https://drones.belgium.be',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Skeyes / drones.belgium.be',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'AT',
    countryName: 'Austria',
    flagEmoji: '\u{1F1E6}\u{1F1F9}',
    region: 'europe',
    authority: {
      name: 'Austro Control',
      acronym: 'ACG',
      website: 'https://www.austrocontrol.at/en/aviation-agency/legal-framework-of-aviation/drones',
      registrationPortal: 'https://www.dronespace.at',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Dronespace.at',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD.MM.YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'PT',
    countryName: 'Portugal',
    flagEmoji: '\u{1F1F5}\u{1F1F9}',
    region: 'europe',
    authority: {
      name: 'Autoridade Nacional da Aviacao Civil',
      acronym: 'ANAC',
      website: 'https://www.anac.pt/vPT/Generico/Drones/Paginas/Drones.aspx',
      registrationPortal: 'https://www.anac.pt',
    },
    regulations: {
      primaryRegulation: 'EU Regulation 2019/947 (EASA)',
      pilotCertName: 'EU Remote Pilot Certificate (A1/A3 or A2)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'EU Delegated Regulation 2019/945',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ANAC Portugal UAS Portal',
    },
    locale: {
      currency: 'EUR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // AFRICA (15)
  // ═══════════════════════════════════════════════════════════════════

  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    flagEmoji: '\u{1F1F3}\u{1F1EC}',
    region: 'africa',
    authority: {
      name: 'Nigerian Civil Aviation Authority',
      acronym: 'NCAA',
      website: 'https://ncaa.gov.ng',
      registrationPortal: 'https://rpas.ncaa.gov.ng',
    },
    regulations: {
      primaryRegulation: 'Nig.CARs Part 21 / NCAA RPAS Regulations 2022',
      pilotCertName: 'RPAS Pilot Certificate / ROC',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'NCAA RPAS Portal',
    },
    locale: {
      currency: 'NGN',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'KE',
    countryName: 'Kenya',
    flagEmoji: '\u{1F1F0}\u{1F1EA}',
    region: 'africa',
    authority: {
      name: 'Kenya Civil Aviation Authority',
      acronym: 'KCAA',
      website: 'https://www.kcaa.or.ke',
      registrationPortal: 'https://www.kcaa.or.ke',
    },
    regulations: {
      primaryRegulation: 'Civil Aviation (Unmanned Aircraft Systems) Regulations 2020',
      pilotCertName: 'Remote Pilot Licence (RPL)',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'KCAA UAS Registration',
    },
    locale: {
      currency: 'KES',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: null,
  },

  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    flagEmoji: '\u{1F1FF}\u{1F1E6}',
    region: 'africa',
    authority: {
      name: 'South African Civil Aviation Authority',
      acronym: 'SACAA',
      website: 'https://www.caa.co.za',
      registrationPortal: 'https://www.caa.co.za/rpas',
    },
    regulations: {
      primaryRegulation: 'SACR Part 101 (Civil Aviation Regulations 2011)',
      pilotCertName: 'Remote Pilot Certificate (RPC)',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'SACAA RPAS Portal',
    },
    locale: {
      currency: 'ZAR',
      dateFormat: 'YYYY/MM/DD',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '10111',
    aviationEmergency: null,
  },

  {
    countryCode: 'GH',
    countryName: 'Ghana',
    flagEmoji: '\u{1F1EC}\u{1F1ED}',
    region: 'africa',
    authority: {
      name: 'Ghana Civil Aviation Authority',
      acronym: 'GCAA',
      website: 'https://www.gcaa.com.gh',
      registrationPortal: 'https://www.gcaa.com.gh',
    },
    regulations: {
      primaryRegulation: 'Ghana Civil Aviation (Drone) Regulations 2020',
      pilotCertName: 'Remote Pilot Licence',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'GCAA Drone Registration',
    },
    locale: {
      currency: 'GHS',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    flagEmoji: '\u{1F1F7}\u{1F1FC}',
    region: 'africa',
    authority: {
      name: 'Rwanda Civil Aviation Authority',
      acronym: 'RCAA',
      website: 'https://www.caa.gov.rw',
      registrationPortal: 'https://www.caa.gov.rw',
    },
    regulations: {
      primaryRegulation: 'Ministerial Order on RPAS Operations',
      pilotCertName: 'RPAS Operator Certificate',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'RCAA UAS Portal',
    },
    locale: {
      currency: 'RWF',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    flagEmoji: '\u{1F1F9}\u{1F1FF}',
    region: 'africa',
    authority: {
      name: 'Tanzania Civil Aviation Authority',
      acronym: 'TCAA',
      website: 'https://www.tcaa.go.tz',
      registrationPortal: 'https://www.tcaa.go.tz',
    },
    regulations: {
      primaryRegulation: 'Civil Aviation (Unmanned Aircraft Systems) Regulations 2018',
      pilotCertName: 'Remote Pilot Licence',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 7,
      laancEquivalent: null,
      authorizationSystem: 'TCAA Drone Permit System',
    },
    locale: {
      currency: 'TZS',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'UG',
    countryName: 'Uganda',
    flagEmoji: '\u{1F1FA}\u{1F1EC}',
    region: 'africa',
    authority: {
      name: 'Uganda Civil Aviation Authority',
      acronym: 'UCAA',
      website: 'https://www.caa.go.ug',
      registrationPortal: 'https://www.caa.go.ug',
    },
    regulations: {
      primaryRegulation: 'Uganda Civil Aviation (Unmanned Aircraft Systems) Regulations 2021',
      pilotCertName: 'Remote Pilot Certificate',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'UCAA UAS Portal',
    },
    locale: {
      currency: 'UGX',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: null,
  },

  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    flagEmoji: '\u{1F1EA}\u{1F1F9}',
    region: 'africa',
    authority: {
      name: 'Ethiopian Civil Aviation Authority',
      acronym: 'ECAA',
      website: 'https://www.ecaa.gov.et',
      registrationPortal: 'https://www.ecaa.gov.et',
    },
    regulations: {
      primaryRegulation: 'ECAA UAS Directive',
      pilotCertName: 'Remote Pilot Licence',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ECAA Authorization',
    },
    locale: {
      currency: 'ETB',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '911',
    aviationEmergency: null,
  },

  {
    countryCode: 'SN',
    countryName: 'Senegal',
    flagEmoji: '\u{1F1F8}\u{1F1F3}',
    region: 'africa',
    authority: {
      name: 'Agence Nationale de l\'Aviation Civile et de la Meteorologie',
      acronym: 'ANACIM',
      website: 'https://www.anacim.sn',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'ANACIM RPAS Regulations',
      pilotCertName: 'Certificat de Telepilote',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ANACIM Authorization',
    },
    locale: {
      currency: 'XOF',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '17',
    aviationEmergency: null,
  },

  {
    countryCode: 'CI',
    countryName: 'Cote d\'Ivoire',
    flagEmoji: '\u{1F1E8}\u{1F1EE}',
    region: 'africa',
    authority: {
      name: 'Autorite Nationale de l\'Aviation Civile',
      acronym: 'ANAC',
      website: 'https://www.anac.ci',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'ANAC RPAS Identification Regulations',
      pilotCertName: 'Certificat de Telepilote',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ANAC Authorization',
    },
    locale: {
      currency: 'XOF',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '110',
    aviationEmergency: null,
  },

  {
    countryCode: 'EG',
    countryName: 'Egypt',
    flagEmoji: '\u{1F1EA}\u{1F1EC}',
    region: 'africa',
    authority: {
      name: 'Egyptian Civil Aviation Authority',
      acronym: 'ECAA',
      website: 'https://www.civilaviation.gov.eg',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'ECAA UAS Regulations',
      pilotCertName: 'UAS Operator Permit',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ECAA / Ministry of Defense Authorization',
    },
    locale: {
      currency: 'EGP',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '122',
    aviationEmergency: null,
  },

  {
    countryCode: 'MA',
    countryName: 'Morocco',
    flagEmoji: '\u{1F1F2}\u{1F1E6}',
    region: 'africa',
    authority: {
      name: 'Direction Generale de l\'Aviation Civile',
      acronym: 'DGAC',
      website: 'https://www.aviation-civile.gov.ma',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'DGAC UAS Authorization Framework',
      pilotCertName: 'Professional Drone Operator Permit',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'DGAC / Wilaya Authorization',
    },
    locale: {
      currency: 'MAD',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '15',
    aviationEmergency: null,
  },

  {
    countryCode: 'CM',
    countryName: 'Cameroon',
    flagEmoji: '\u{1F1E8}\u{1F1F2}',
    region: 'africa',
    authority: {
      name: 'Cameroon Civil Aviation Authority',
      acronym: 'CCAA',
      website: 'https://www.ccaa.aero',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'CCAA RPAS Regulations',
      pilotCertName: 'RPAS Operator Permit',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CCAA Authorization',
    },
    locale: {
      currency: 'XAF',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '117',
    aviationEmergency: null,
  },

  {
    countryCode: 'CD',
    countryName: 'Democratic Republic of the Congo',
    flagEmoji: '\u{1F1E8}\u{1F1E9}',
    region: 'africa',
    authority: {
      name: 'Autorite de l\'Aviation Civile de la RDC',
      acronym: 'AAC/RDC',
      website: 'https://www.aac-rdc.cd',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'AAC/RDC RPAS Operating Regulations',
      pilotCertName: 'RPAS Operating Permit',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'AAC/RDC Authorization',
    },
    locale: {
      currency: 'CDF',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'MZ',
    countryName: 'Mozambique',
    flagEmoji: '\u{1F1F2}\u{1F1FF}',
    region: 'africa',
    authority: {
      name: 'Instituto de Aviacao Civil de Mocambique',
      acronym: 'IACM',
      website: 'https://www.iacm.gov.mz',
      registrationPortal: null,
    },
    regulations: {
      primaryRegulation: 'IACM RPAS Regulations',
      pilotCertName: 'RPAS Operator Authorization',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 100,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'IACM Authorization',
    },
    locale: {
      currency: 'MZN',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '119',
    aviationEmergency: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // MIDDLE EAST (5)
  // ═══════════════════════════════════════════════════════════════════

  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    flagEmoji: '\u{1F1E6}\u{1F1EA}',
    region: 'middle_east',
    authority: {
      name: 'General Civil Aviation Authority',
      acronym: 'GCAA',
      website: 'https://www.gcaa.gov.ae',
      registrationPortal: 'https://www.gcaa.gov.ae/en/pages/UASRegistration.aspx',
    },
    regulations: {
      primaryRegulation: 'UAE Federal Decree-Law No. 8/2023 on Drones',
      pilotCertName: 'GCAA Drone Operator Certificate',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'GCAA UAS Remote ID Regulation',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'GCAA / DCAA (Dubai) UAS Platform',
    },
    locale: {
      currency: 'AED',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: null,
  },

  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    flagEmoji: '\u{1F1F8}\u{1F1E6}',
    region: 'middle_east',
    authority: {
      name: 'General Authority of Civil Aviation',
      acronym: 'GACA',
      website: 'https://www.gaca.gov.sa',
      registrationPortal: 'https://uas.gaca.gov.sa',
    },
    regulations: {
      primaryRegulation: 'GACA Advisory Circulars on UAS Operations',
      pilotCertName: 'GACA UAS Operator Certificate',
      registrationRequired: true,
      remoteIdRequired: 'planned',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'GACA UAS Portal',
    },
    locale: {
      currency: 'SAR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '911',
    aviationEmergency: null,
  },

  {
    countryCode: 'IL',
    countryName: 'Israel',
    flagEmoji: '\u{1F1EE}\u{1F1F1}',
    region: 'middle_east',
    authority: {
      name: 'Civil Aviation Authority of Israel',
      acronym: 'CAAI',
      website: 'https://www.gov.il/en/departments/civil_aviation_authority',
      registrationPortal: 'https://www.gov.il/en/departments/civil_aviation_authority',
    },
    regulations: {
      primaryRegulation: 'Aviation Regulations (UAS) 2022',
      pilotCertName: 'UAS Pilot Certificate',
      registrationRequired: true,
      remoteIdRequired: 'planned',
      remoteIdRegulation: null,
      maxAltitudeFt: 164,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAAI Flight Authorization',
    },
    locale: {
      currency: 'ILS',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '100',
    aviationEmergency: null,
  },

  {
    countryCode: 'QA',
    countryName: 'Qatar',
    flagEmoji: '\u{1F1F6}\u{1F1E6}',
    region: 'middle_east',
    authority: {
      name: 'Qatar Civil Aviation Authority',
      acronym: 'QCAA',
      website: 'https://caa.gov.qa',
      registrationPortal: 'https://caa.gov.qa/en/UA-Drones',
    },
    regulations: {
      primaryRegulation: 'QCAA UAS Regulations 2021',
      pilotCertName: 'QCAA Drone Operator Permit',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'QCAA UAS Registration',
    },
    locale: {
      currency: 'QAR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: null,
  },

  {
    countryCode: 'OM',
    countryName: 'Oman',
    flagEmoji: '\u{1F1F4}\u{1F1F2}',
    region: 'middle_east',
    authority: {
      name: 'Public Authority for Civil Aviation',
      acronym: 'PACA',
      website: 'https://www.paca.gov.om',
      registrationPortal: 'https://www.paca.gov.om',
    },
    regulations: {
      primaryRegulation: 'PACA RPAS Regulations',
      pilotCertName: 'RPA Operator Permit',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'PACA Drone Permit System',
    },
    locale: {
      currency: 'OMR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '9999',
    aviationEmergency: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // ASIA-PACIFIC (11)
  // ═══════════════════════════════════════════════════════════════════

  {
    countryCode: 'AU',
    countryName: 'Australia',
    flagEmoji: '\u{1F1E6}\u{1F1FA}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Safety Authority',
      acronym: 'CASA',
      website: 'https://www.casa.gov.au/drones',
      registrationPortal: 'https://my.casa.gov.au',
    },
    regulations: {
      primaryRegulation: 'CASR Part 101 / CASA Advisory Circular 101-01',
      pilotCertName: 'RPA Operator Accreditation / Remote Pilot Licence (RePL)',
      registrationRequired: true,
      remoteIdRequired: 'planned',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CASA myCASA Portal',
    },
    locale: {
      currency: 'AUD',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '000',
    aviationEmergency: '1300-737-032',
  },

  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    flagEmoji: '\u{1F1F3}\u{1F1FF}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Authority of New Zealand',
      acronym: 'CAA NZ',
      website: 'https://www.aviation.govt.nz/drones',
      registrationPortal: 'https://www.aviation.govt.nz/drones',
    },
    regulations: {
      primaryRegulation: 'Civil Aviation Rules Part 101 / Part 102',
      pilotCertName: 'Part 102 Unmanned Aircraft Operator Certificate',
      registrationRequired: false,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAA NZ Airshare',
    },
    locale: {
      currency: 'NZD',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '111',
    aviationEmergency: null,
  },

  {
    countryCode: 'JP',
    countryName: 'Japan',
    flagEmoji: '\u{1F1EF}\u{1F1F5}',
    region: 'asia_pacific',
    authority: {
      name: 'Ministry of Land, Infrastructure, Transport and Tourism',
      acronym: 'MLIT',
      website: 'https://www.mlit.go.jp/koku/koku_ua_index.html',
      registrationPortal: 'https://www.dips-reg.mlit.go.jp',
    },
    regulations: {
      primaryRegulation: 'Aviation Act Amendments (UAS) 2022',
      pilotCertName: 'Unmanned Aircraft Pilot Certificate (Level 1-4)',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'Aviation Act Article 132-88',
      maxAltitudeFt: 492,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'DIPS (Drone Information Platform System)',
    },
    locale: {
      currency: 'JPY',
      dateFormat: 'YYYY/MM/DD',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '110',
    aviationEmergency: null,
  },

  {
    countryCode: 'KR',
    countryName: 'South Korea',
    flagEmoji: '\u{1F1F0}\u{1F1F7}',
    region: 'asia_pacific',
    authority: {
      name: 'Ministry of Land, Infrastructure and Transport / Korea Office of Civil Aviation',
      acronym: 'MOLIT / KOCA',
      website: 'https://www.molit.go.kr',
      registrationPortal: 'https://drone.onestop.go.kr',
    },
    regulations: {
      primaryRegulation: 'Aviation Safety Act / Drone Act (2021)',
      pilotCertName: 'Remote Pilot Licence (Class I-IV)',
      registrationRequired: true,
      remoteIdRequired: 'planned',
      remoteIdRegulation: null,
      maxAltitudeFt: 492,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Drone One-Stop Service (drone.onestop.go.kr)',
    },
    locale: {
      currency: 'KRW',
      dateFormat: 'YYYY-MM-DD',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'IN',
    countryName: 'India',
    flagEmoji: '\u{1F1EE}\u{1F1F3}',
    region: 'asia_pacific',
    authority: {
      name: 'Directorate General of Civil Aviation',
      acronym: 'DGCA',
      website: 'https://dgca.gov.in',
      registrationPortal: 'https://digitalsky.dgca.gov.in',
    },
    regulations: {
      primaryRegulation: 'Drone Rules 2021 / UAS Rules 2021',
      pilotCertName: 'Remote Pilot Certificate',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'NPNT (No Permission No Takeoff)',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: 'Digital Sky Platform',
      authorizationSystem: 'Digital Sky / AirSewa',
    },
    locale: {
      currency: 'INR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'SG',
    countryName: 'Singapore',
    flagEmoji: '\u{1F1F8}\u{1F1EC}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Authority of Singapore',
      acronym: 'CAAS',
      website: 'https://www.caas.gov.sg/public-passengers/unmanned-aircraft',
      registrationPortal: 'https://www.caas.gov.sg',
    },
    regulations: {
      primaryRegulation: 'Unmanned Aircraft (Public Safety and Security) Act 2015',
      pilotCertName: 'Unmanned Aircraft Pilot Licence (UAPL) / UABTC',
      registrationRequired: true,
      remoteIdRequired: 'planned',
      remoteIdRegulation: null,
      maxAltitudeFt: 200,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAAS OneMap / UA Management System',
    },
    locale: {
      currency: 'SGD',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: null,
  },

  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    flagEmoji: '\u{1F1F2}\u{1F1FE}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Authority of Malaysia',
      acronym: 'CAAM',
      website: 'https://www.caam.gov.my',
      registrationPortal: 'https://www.caam.gov.my',
    },
    regulations: {
      primaryRegulation: 'Malaysian Civil Aviation Directive (MCAD) 9801',
      pilotCertName: 'UAS Operator Certificate',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 20,
      laancEquivalent: null,
      authorizationSystem: 'CAAM UAS Portal',
    },
    locale: {
      currency: 'MYR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '999',
    aviationEmergency: null,
  },

  {
    countryCode: 'TH',
    countryName: 'Thailand',
    flagEmoji: '\u{1F1F9}\u{1F1ED}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Authority of Thailand',
      acronym: 'CAAT',
      website: 'https://www.caat.or.th',
      registrationPortal: 'https://uav.caat.or.th',
    },
    regulations: {
      primaryRegulation: 'CAAT Notification on UAS Operations (B.E. 2558/2015)',
      pilotCertName: 'UAS Operator Registration',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 295,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAAT UAV Registration Portal',
    },
    locale: {
      currency: 'THB',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '191',
    aviationEmergency: null,
  },

  {
    countryCode: 'PH',
    countryName: 'Philippines',
    flagEmoji: '\u{1F1F5}\u{1F1ED}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Authority of the Philippines',
      acronym: 'CAAP',
      website: 'https://www.caap.gov.ph',
      registrationPortal: 'https://www.caap.gov.ph/rpas-regulations',
    },
    regulations: {
      primaryRegulation: 'CAAP RPAS Memorandum Circular (MC) 2020-001',
      pilotCertName: 'RPAS Operator Certificate',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAAP RPAS Portal',
    },
    locale: {
      currency: 'PHP',
      dateFormat: 'MM/DD/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '911',
    aviationEmergency: null,
  },

  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    flagEmoji: '\u{1F1EE}\u{1F1E9}',
    region: 'asia_pacific',
    authority: {
      name: 'Directorate General of Civil Aviation',
      acronym: 'DGCA',
      website: 'https://hubud.dephub.go.id',
      registrationPortal: 'https://hubud.dephub.go.id',
    },
    regulations: {
      primaryRegulation: 'PM 37/2020 (Minister of Transport Regulation)',
      pilotCertName: 'UAS Operator Certificate',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 492,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'DGCA UAS Authorization',
    },
    locale: {
      currency: 'IDR',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '112',
    aviationEmergency: null,
  },

  {
    countryCode: 'CN',
    countryName: 'China',
    flagEmoji: '\u{1F1E8}\u{1F1F3}',
    region: 'asia_pacific',
    authority: {
      name: 'Civil Aviation Administration of China',
      acronym: 'CAAC',
      website: 'https://www.caac.gov.cn',
      registrationPortal: 'https://uas.caac.gov.cn',
    },
    regulations: {
      primaryRegulation: 'Interim Regulations on UAS Flight Management (2024) / Civil Aviation Law Amendments 2025',
      pilotCertName: 'UAS Operator Certificate / AOPA China License',
      registrationRequired: true,
      remoteIdRequired: 'required',
      remoteIdRegulation: 'National Standards GB/T (Real-Name Registration 2026)',
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'CAAC UAS Real-Name Registration System',
    },
    locale: {
      currency: 'CNY',
      dateFormat: 'YYYY-MM-DD',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '110',
    aviationEmergency: null,
  },

  // ═══════════════════════════════════════════════════════════════════
  // SOUTH AMERICA (5)
  // ═══════════════════════════════════════════════════════════════════

  {
    countryCode: 'BR',
    countryName: 'Brazil',
    flagEmoji: '\u{1F1E7}\u{1F1F7}',
    region: 'south_america',
    authority: {
      name: 'Agencia Nacional de Aviacao Civil',
      acronym: 'ANAC',
      website: 'https://www.gov.br/anac/en/topics/drones',
      registrationPortal: 'https://sistemas.anac.gov.br/sisant',
    },
    regulations: {
      primaryRegulation: 'RBAC-E 94 / RBAC 100 (proposed)',
      pilotCertName: 'Certificado de Piloto de RPAS',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'SISANT / DECEA SARPAS',
    },
    locale: {
      currency: 'BRL',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '190',
    aviationEmergency: null,
  },

  {
    countryCode: 'CO',
    countryName: 'Colombia',
    flagEmoji: '\u{1F1E8}\u{1F1F4}',
    region: 'south_america',
    authority: {
      name: 'Aeronautica Civil de Colombia',
      acronym: 'Aerocivil',
      website: 'https://www.aerocivil.gov.co',
      registrationPortal: 'https://www.aerocivil.gov.co',
    },
    regulations: {
      primaryRegulation: 'RAC Part 17 / Circular Reglamentaria 002',
      pilotCertName: 'Licencia de Explotador de UAS',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'Aerocivil UAS Registration',
    },
    locale: {
      currency: 'COP',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '123',
    aviationEmergency: null,
  },

  {
    countryCode: 'AR',
    countryName: 'Argentina',
    flagEmoji: '\u{1F1E6}\u{1F1F7}',
    region: 'south_america',
    authority: {
      name: 'Administracion Nacional de Aviacion Civil',
      acronym: 'ANAC',
      website: 'https://www.argentina.gob.ar/anac',
      registrationPortal: 'https://www.argentina.gob.ar/anac/drones',
    },
    regulations: {
      primaryRegulation: 'RAAC Part 100 (Res. 319/2025)',
      pilotCertName: 'Certificado de Piloto de VANT',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'ANAC VANT Portal',
    },
    locale: {
      currency: 'ARS',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '911',
    aviationEmergency: null,
  },

  {
    countryCode: 'CL',
    countryName: 'Chile',
    flagEmoji: '\u{1F1E8}\u{1F1F1}',
    region: 'south_america',
    authority: {
      name: 'Direccion General de Aeronautica Civil',
      acronym: 'DGAC',
      website: 'https://www.dgac.gob.cl',
      registrationPortal: 'https://www.dgac.gob.cl',
    },
    regulations: {
      primaryRegulation: 'DAN 151 Edicion 3 (2024)',
      pilotCertName: 'Licencia de Piloto de RPAS / Certificacion DGAC',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'DGAC Authorization System',
    },
    locale: {
      currency: 'CLP',
      dateFormat: 'DD-MM-YYYY',
      timeFormat: '24h',
      distanceUnit: 'meters',
      altitudeUnit: 'meters',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '131',
    aviationEmergency: null,
  },

  {
    countryCode: 'PE',
    countryName: 'Peru',
    flagEmoji: '\u{1F1F5}\u{1F1EA}',
    region: 'south_america',
    authority: {
      name: 'Direccion General de Aeronautica Civil',
      acronym: 'DGAC',
      website: 'https://www.gob.pe/dgac',
      registrationPortal: 'https://www.gob.pe/dgac',
    },
    regulations: {
      primaryRegulation: 'NTC 001-2019 (RPAS Technical Standard)',
      pilotCertName: 'Licencia de Piloto de RPAS',
      registrationRequired: true,
      remoteIdRequired: 'not_required',
      remoteIdRegulation: null,
      maxAltitudeFt: 400,
      maxWeightKg: 25,
      laancEquivalent: null,
      authorizationSystem: 'DGAC Tarjeta de Registro',
    },
    locale: {
      currency: 'PEN',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: '12h',
      distanceUnit: 'meters',
      altitudeUnit: 'feet',
      speedUnit: 'km/h',
      weightUnit: 'kilograms',
      temperatureUnit: 'celsius',
    },
    emergencyNumber: '105',
    aviationEmergency: null,
  },
];

// ═══════════════════════════════════════════════════════════════════
// Helper functions
// ═══════════════════════════════════════════════════════════════════

/** Look up a country's regulatory authority by ISO 3166-1 alpha-2 code */
export function getAuthorityByCountryCode(code: string): CountryAuthority | undefined {
  return GLOBAL_REGULATORY_AUTHORITIES.find(
    (c) => c.countryCode === code.toUpperCase(),
  );
}

/** Get all countries in a region */
export function getAuthoritiesByRegion(region: CountryAuthority['region']): CountryAuthority[] {
  return GLOBAL_REGULATORY_AUTHORITIES.filter((c) => c.region === region);
}

/** Get all countries that require Remote ID */
export function getCountriesRequiringRemoteId(): CountryAuthority[] {
  return GLOBAL_REGULATORY_AUTHORITIES.filter(
    (c) => c.regulations.remoteIdRequired === 'required',
  );
}

/** Get all countries that have an airspace authorization system (LAANC equivalent) */
export function getCountriesWithAuthorizationSystem(): CountryAuthority[] {
  return GLOBAL_REGULATORY_AUTHORITIES.filter(
    (c) => c.regulations.laancEquivalent !== null,
  );
}

/** Get all supported country codes for form dropdowns */
export function getSupportedCountryCodes(): { code: string; name: string; flag: string }[] {
  return GLOBAL_REGULATORY_AUTHORITIES.map((c) => ({
    code: c.countryCode,
    name: c.countryName,
    flag: c.flagEmoji,
  }));
}

/** Count of supported countries */
export const SUPPORTED_COUNTRY_COUNT = GLOBAL_REGULATORY_AUTHORITIES.length;
